name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Process domain data
        run: |
          python scripts/convert_csv_to_json.py

      - name: Create and populate build directory
        shell: bash
        run: |
          # Create fresh build directory
          rm -rf build
          mkdir build

          # Copy HTML files to build root
          cp src/*.html build/

          # Copy asset directories
          cp -r src/css build/
          cp -r src/js build/
          cp -r src/domains build/

          # Copy data directory
          mkdir -p build/data/output
          cp -r data/output/* build/data/output/

          # Create required files
          touch build/.nojekyll
          echo "topdomain.club" > build/CNAME

          # Debug: List contents
          echo "Build directory structure:"
          ls -la build/
          echo "\nCSS directory:"
          ls -la build/css
          echo "\nJS directory:"
          ls -la build/js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true