name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Process domain data
        run: |
          python scripts/convert_csv_to_json.py

      - name: Debug source directories
        run: |
          echo "Contents of data/output directory:"
          ls -la data/output/
          echo "=============================="
          echo "Source custom_previews count:"
          find data/output/custom_previews -type f | wc -l
          echo "Files in data/output/custom_previews:"
          ls -la data/output/custom_previews/

      - name: Create build directory
        shell: bash
        run: |
          # Create build directory
          mkdir -p build

          # Copy HTML files from docs instead of src
          cp docs/*.html build/
          
          # Copy asset directories from docs
          cp -r docs/css build/
          cp -r docs/js build/
          cp -r docs/domains build/
          
          # Debug before data copy
          echo "=============================="
          echo "Build directory structure before data copy:"
          ls -la build/
          
          # Create data directory
          mkdir -p build/data/output/custom_previews
          
          # Copy data files with verbose output
          echo "=============================="
          echo "Copying data files..."
          cp -rv data/output/* build/data/output/
          
          # Debug after data copy
          echo "=============================="
          echo "Build custom_previews count:"
          find build/data/output/custom_previews -type f | wc -l
          echo "Files in build/data/output/custom_previews:"
          ls -la build/data/output/custom_previews/
          
          # Create required files
          touch build/.nojekyll
          echo "topdomain.club" > build/CNAME
          
          # Final debug: List full build directory structure
          echo "=============================="
          echo "Final build directory structure:"
          find build -type f | sort

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true
          force: true
          commit-message: "Deploy site with force option"